comment:
  layout: header, changes, diff, sunburst

coverage:
  status:
    project:
      default:
        target: auto
        threshold: '0%'

    patch:
      default:
        target: 75%
        only_pulls: true

github_checks:
  annotations: false

ignore:
  - '**/*_test.go'
  - integration/*
  - scripts/*
  - internal/*
