# From https://github.com/alexellis/derek

curators:
 - pchico83 
 - rberrelleza 
 - rlamana

features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes

contributing_url: https://github.com/okteto/okteto/blob/master/contributing.md
