maintainers:
  - pchico83
  - rberrelleza
  - rlamana
  - ifbyol
  - jLopezbarb

features:
  - dco_check
  - pr_description_required

contributing_url: https://github.com/okteto/okteto/blob/master/contributing.md
