run:
  modules-download-mode: readonly

output:
  print-issued-lines: false
  sort-results: true

linters-settings:
  unparam:
    # Inspect exported functions.
    #
    # Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    #
    check-exported: true
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: true
  tenv:
    # The option `all` will run against whole test files (`_test.go`) regardless of method/function signatures.
    # Otherwise, only methods that take `*testing.T`, `*testing.B`, and `testing.TB` as arguments are checked.
    # Default: false
    all: true
  govet:
    enable:
      - fieldalignment
  goheader:
    values:
      regexp:
        YEAR: 2023|2024
    template-path: .copyright-header.tmpl
  mnd:
    checks:
      - argument
      - case
      - condition
      # - operation
      # - return
      # - assign
    ignored-functions:
      - '\.NewWriter'
      - '\.NewTabWriter'
      - '\.WriteFile'
      - '^time.'
      - '^os.'
      - '^bcrypt.'
      - '^math.'
      - '^big.'
      - '\.SetIndent'
      - int
      - make
      - '\.WithTimeout'
  revive:
    rules:
      - name: exported

# All possible linters can be found https://golangci-lint.run/usage/linters/
linters:
  enable:
    - errcheck
    - gosimple
    - typecheck
    - govet
    - ineffassign
    - unused
    - unparam
    - tenv
    - tparallel
    - gci
    - goheader
    - unconvert
    - predeclared
    - asciicheck
    - asasalint
    - bidichk
    - decorder
    - exportloopref
    - makezero
    - mnd
    - musttag
    - bodyclose
    - durationcheck
    - exhaustive
    - revive

issues:
  include:
    - EXC0014 # EXC0014 revive: comment on exported (.+) should be of the form "(.+)..."

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - errcheck
    - linters:
        - unparam
      # exclude from linting the custom implementation for "MarshalYAML"
      text: 'MarshalYAML()'
