name: pre-commit

on: [pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  pre-commit:
    name: Run pre-commit # https://pre-commit.com/
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ${{ github.ref }} ( ${{ github.sha }} )'
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6 # https://www.python.org/
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies # https://pip.pypa.io/en/stable/
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> "$GITHUB_ENV"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: pre-commit run --all-files
