name: Run CircleCI from label

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  run-e2e-windows:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-windows') && !contains(github.event.pull_request.labels.*.name, 'run-e2e')
    runs-on: ubuntu-latest
    steps:
      - name: Run Windows e2e tests on CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: "run-e2e-windows"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

  run-e2e-unix:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-unix') && !contains(github.event.pull_request.labels.*.name, 'run-e2e')
    runs-on: ubuntu-latest
    steps:
      - name: Run UNIX e2e tests on CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: "run-e2e-unix"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

  run-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e')
    runs-on: ubuntu-latest
    steps:
      - name: Run e2e tests on CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: "run-e2e"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
