name: Run CircleCI from label

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  run-e2e-windows:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-windows') && !contains(github.event.pull_request.labels.*.name, 'run-e2e')
    uses: ./.github/workflows/trigger-circleci-e2e.yml
    with:
      gha_meta: "run-e2e-windows"
      branch: ${{ github.head_ref }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

  run-e2e-unix:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-unix') && !contains(github.event.pull_request.labels.*.name, 'run-e2e')
    uses: ./.github/workflows/trigger-circleci-e2e.yml
    with:
      gha_meta: "run-e2e-unix"
      branch: ${{ github.head_ref }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      CCI_TOKEN: ${{ secrets.CCI_TOKEN }}

  run-e2e:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e')
    uses: ./.github/workflows/trigger-circleci-e2e.yml
    with:
      gha_meta: "run-e2e"
      branch: ${{ github.head_ref }}
      pr_number: ${{ github.event.pull_request.number }}
    secrets:
      CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
